# Generated by Django 4.2.1 on 2023-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarditem',
            name='title',
            field=models.TextField(),
        ),
    ]
