# Generated by Django 4.2.1 on 2023-06-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboarditem_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardItem',
            new_name='Article',
        ),
    ]
